### ISSUE TITLE
Loss does not fall

### ISSUE THREAD

**Issue by AuroraYXL** [megvii-research/BasesHomo#3]
How to solve the second problem? Without changing any code and parameters, my loss will not decline after the first 5k iterations (single GPU operation).p1 is feature loss,p2 is total loss
![1](https://user-images.githubusercontent.com/70422251/143664772-0af9ceb5-cd20-4b37-b05f-895129e31a1e.jpg)
![2](https://user-images.githubusercontent.com/70422251/143664776-4ba9018a-51d4-4d73-a85f-63db6ae46a04.jpg)

**Comment by MingboHong** [comment]
You can try changing "batch_size: 16" to "batch_size: 32"

**Comment by lhaippp** [comment]
Please provide your python environments.

**Comment by AuroraYXL** [comment]
> You can try changing "batch_size: 16" to "batch_size: 32"

I did but it also didn't work

**Comment by AuroraYXL** [comment]
> Please provide your python environments.

Python 3.7.9
Pytorch 1.7.1
numpy 1.19.2

NVIDIA RTX 1080 Ti

**Comment by lhaippp** [comment]
Please follow the "Requirements" in the README file to reset the environments.
